[window]
# decorations = "none"
opacity = 0.9
padding = { x = 2, y = 2 }
startup_mode = "Maximized" 
option_as_alt = "Both"

[env]
TERM = "xterm-256color"

[font]
size = 12.0

[font.normal]
family = "VictorMono Nerd Font"

[general]
live_config_reload = true

import = ["~/.config/alacritty/themes/ayu.toml"]
