import = [
    "~/.config/alacritty/themes/themes/catppuccin_mocha.toml"
]

[font]
offset = { x = 1, y = 0 }
size = 12
normal.family = "VictorMono Nerd Font"

[window]
opacity = 0.9

[env]
TERM = "xterm-256color"
