import = [
    "~/.config/alacritty/themes/themes/cyberdream.toml"
]

[font]
offset = { x = 1, y = 0 }
size = 12
normal.family = "MonoLisa"

[window]
opacity = 0.7
blur = true

[env]
TERM = "xterm-256color"
