[font]
offset = { x = 1, y = 0 }
size = 12
normal.family = "MonoLisa Nerd Font"

[env]
TERM = "xterm-256color"

[colors.primary]
background = '#070e11'
foreground = '#f5f5f5'

[colors.normal]
black   = "#10181B"
red     = '#fa5e86'
green   = '#00d992'
yellow  = '#f8ff18'
blue    = '#b4b4b4'
magenta = '#d5d5d5'
cyan    = '#f5f5f5'
white   = '#ffffff'

# return {
#   background = "#070e11",
#   primary = "#00d992",
#   secondary = "#E9F5E9",
#   noir_0 = "#ffffff",
#   noir_1 = "#f5f5f5",
#   noir_2 = "#d5d5d5",
#   noir_3 = "#b4b4b4",
#   noir_4 = "#a7a7a7",
#   noir_5 = "#949494",
#   noir_6 = "#737373",
#   noir_7 = "#3A4649",
#   noir_8 = "#1D2526",
#   noir_9 = "#10181B",
#   diagnostic_error = "#fa5e86",
#   diagnostic_warning = "#ffb717",
#   diagnostic_info = "#00d992",
#   diagnostic_hint = "#00d992",
#   diff_add = "#00d992",
#   diff_change = "#90a7f8",
#   diff_delete = "#fa5e86",
# }
